apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: dev
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
  type: ClusterIP
