apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  labels:
    app: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: luispi18/cloud-config:latest
        ports:
        - containerPort: 9296
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE
          value: "cloud-config"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9296
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9296
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5