apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: dev
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
  type: ClusterIP
